// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Jens Köhler
// Assisted-by: Claude Code (Anthropic)
// Generated by tools/protocol.py from protocol.toml. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

/// The evaluation protocol. See protocol.toml for what each value means
/// and why it is the value it is.
namespace md::protocol {

inline constexpr std::uint32_t decision_interval = 4;
inline constexpr std::uint64_t max_ticks = 120000;
inline constexpr float aim_trail = 0.875f;
inline constexpr std::size_t per_split = 32;
inline constexpr std::size_t validation_offset = 0;
inline constexpr std::size_t canonical_offset = 32;
inline constexpr std::string_view canonical_split = "canonical";
inline constexpr std::string_view validation_split = "validation";
inline constexpr std::string_view inference_device = "cpu";
inline constexpr std::string_view policy_magic = "MDPOLICY";
inline constexpr std::uint32_t policy_container_version = 1;
inline constexpr std::string_view runs_dir = "runs";
inline constexpr std::string_view models_dir = "models";
inline constexpr std::string_view matches_dir = "matches";

} // namespace md::protocol
