// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Jens Köhler
// Assisted-by: Claude Code (Anthropic)
//
// The native `.mdp` reader, and the claim that matters: **this implementation
// and the Python one compute the same thing from the same file.**
//
// `python/tests/test_export_policy.py` writes `tiny-policy-parity.json` — fixed
// observations, legal masks, and the logits, value and chosen action its own
// forward pass produced. Nothing here recomputes those; they are read and
// asserted against. A fixture generated by both sides at build time would be two
// implementations of the same bug, and the entire point is to catch these two
// disagreeing.
//
// The rest is refusals. This reader is handed files a person may have
// downloaded, so every malformed case is a promise that it throws rather than
// reading past the end of a buffer.
#include "md/agent/eval.hpp"
#include "md/agent/policy.hpp"
#include "md/observation.hpp"

#include <array>
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <nlohmann/json.hpp>
#include <span>
#include <string>
#include <utility>
#include <vector>

namespace {

/// Where `tools/make_policy_fixture.py` puts what it writes. Passed in by CMake
/// so the tests run from any working directory, which `ctest` does not promise.
std::filesystem::path fixture(const std::string& name) {
    return std::filesystem::path{MD_POLICY_FIXTURES} / name;
}

std::vector<char> read_all(const std::filesystem::path& path) {
    std::ifstream file{path, std::ios::binary};
    return {std::istreambuf_iterator<char>{file}, std::istreambuf_iterator<char>{}};
}

/// Write `bytes` somewhere temporary and hand back the path. The mutation tests
/// all need a broken copy of a good file, and none of them may touch the fixture.
std::filesystem::path scratch(const std::string& name, const std::vector<char>& bytes) {
    const std::filesystem::path path =
        std::filesystem::temp_directory_path() / ("md-policy-test-" + name);
    std::ofstream out{path, std::ios::binary | std::ios::trunc};
    out.write(bytes.data(), static_cast<std::streamsize>(bytes.size()));
    return path;
}

/// The parity fixture, parsed just far enough to drive the assertions. A JSON
/// library is already a dependency of the reader under test, so using it here
/// costs nothing and keeps the test honest about the file's real shape.
struct Sample {
    std::vector<float> observation;
    std::vector<std::uint8_t> legal;
    std::vector<float> logits;
    float value = 0.0F;
    std::uint32_t action = 0;
};

std::vector<Sample> parity_samples(const std::string& name = "tiny-policy-parity.json") {
    std::ifstream file{fixture(name)};
    REQUIRE(file.good());
    const nlohmann::json payload = nlohmann::json::parse(file);

    // The fixture states the sentinel it used, and this asserts the two agree
    // rather than assuming it: a change to MASKED_LOGIT on one side would
    // otherwise show up as a mysterious parity failure on masked entries only.
    REQUIRE(payload.at("masked_logit").get<double>() ==
            static_cast<double>(md::agent::Policy::masked_logit));

    std::vector<Sample> samples;
    for (const nlohmann::json& entry : payload.at("samples")) {
        Sample sample;
        sample.observation = entry.at("observation").get<std::vector<float>>();
        for (const int flag : entry.at("legal").get<std::vector<int>>()) {
            sample.legal.push_back(static_cast<std::uint8_t>(flag));
        }
        sample.logits = entry.at("logits").get<std::vector<float>>();
        sample.value = entry.at("value").get<float>();
        sample.action = entry.at("action").get<std::uint32_t>();
        samples.push_back(std::move(sample));
    }
    return samples;
}

} // namespace

TEST_CASE("A policy file loads and describes itself", "[unit][agent][policy]") {
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-policy.mdp"));
    CHECK(policy.schema() == 1u);
    CHECK(policy.observation_size() == 12u);
    CHECK(policy.action_count() == 7u);
    CHECK(policy.architecture() == "mlp");
    // The name the HUD puts on screen while this agent plays. It comes from the
    // file rather than the filename, because a path is not a name.
    CHECK(policy.display_name() == "Tiny Fixture");
}

TEST_CASE("A policy can be described without reading its weights", "[unit][agent][policy]") {
    // What a model browser needs. Eight entries on a screen must not cost eight
    // multi-megabyte tensor reads and eight checksum verifications.
    const auto described = md::agent::Policy::describe(fixture("tiny-policy.mdp"));
    CHECK(described.schema == 1u);
    CHECK(described.observation_size == 12u);
    CHECK(described.action_count == 7u);
    CHECK(described.architecture == "mlp");
    // The same name `load` reports, out of the same place in the manifest — two
    // rules would show one name in the browser and another in the HUD.
    CHECK(described.display_name == "Tiny Fixture");
    CHECK(described.display_name ==
          md::agent::Policy::load(fixture("tiny-policy.mdp")).display_name());
}

TEST_CASE("Describing something that is not a policy is refused", "[unit][agent][policy]") {
    // The browser lists what it can describe, so a file that would fail on
    // Enter has to fail here instead — silently absent beats offered and broken.
    const std::string text{"this is not a policy file at all"};
    const auto junk = scratch("not-a-policy", std::vector<char>{text.begin(), text.end()});
    CHECK_THROWS_AS(md::agent::Policy::describe(junk), md::agent::Policy::Error);
    CHECK_THROWS_AS(md::agent::Policy::describe("no-such-file.mdp"), md::agent::Policy::Error);
}

TEST_CASE("The native forward pass agrees with the Python one, sample for sample",
          "[unit][agent][policy][parity]") {
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-policy.mdp"));
    const std::vector<Sample> samples = parity_samples();
    REQUIRE(samples.size() == 12u);

    std::vector<float> logits(policy.action_count());
    for (std::size_t i = 0; i < samples.size(); ++i) {
        INFO("sample " << i);
        const Sample& sample = samples[i];
        const md::agent::Policy::Decision decision =
            policy.act(sample.observation, sample.legal, logits);

        // The whole vector, not only the argmax: two implementations can agree
        // on the chosen action and disagree about everything behind it, and the
        // disagreement only shows up as a different move a thousand ticks later.
        for (std::size_t a = 0; a < logits.size(); ++a) {
            INFO("action " << a);
            CHECK(logits[a] == Catch::Approx(sample.logits[a]).margin(2e-4));
        }
        CHECK(decision.value == Catch::Approx(sample.value).margin(2e-4));
        CHECK(decision.action == sample.action);
    }
}

TEST_CASE("A relational policy file loads and describes itself", "[unit][agent][policy]") {
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-entity.mdp"));
    CHECK(policy.schema() == 1u);
    CHECK(policy.architecture() == "entity");
    CHECK(policy.display_name() == "Tiny Relational");
    // Not tiny, and deliberately so: the reader takes its slot counts from the
    // ObsSpec it was compiled with, so the fixture has to be a policy for *this*
    // simulation or it would be refused by the very check being relied on.
    CHECK(policy.observation_size() == md::ObsSpec{}.size());
}

TEST_CASE("The relational forward pass agrees with the Python one, sample for sample",
          "[unit][agent][policy][parity]") {
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-entity.mdp"));
    const std::vector<Sample> samples = parity_samples("tiny-entity-parity.json");
    REQUIRE(samples.size() == 5u);

    std::vector<float> logits(policy.action_count());
    for (std::size_t i = 0; i < samples.size(); ++i) {
        INFO("sample " << i);
        const Sample& sample = samples[i];
        REQUIRE(sample.observation.size() == policy.observation_size());
        const md::agent::Policy::Decision decision =
            policy.act(sample.observation, sample.legal, logits);

        for (std::size_t a = 0; a < logits.size(); ++a) {
            INFO("action " << a);
            CHECK(logits[a] == Catch::Approx(sample.logits[a]).margin(2e-4));
        }
        CHECK(decision.value == Catch::Approx(sample.value).margin(2e-4));
        CHECK(decision.action == sample.action);
    }
}

TEST_CASE("An empty field drives the attention's zero path", "[unit][agent][policy][parity]") {
    // Sample zero has no live threat, interceptor or blast. `_CrossAttention`
    // scales its output by `has_entity`, so both attention blocks must produce
    // an exact zero *including their output bias*; an implementation returning
    // the bias there passes every busy sample and disagrees on every quiet one.
    const std::vector<Sample> samples = parity_samples("tiny-entity-parity.json");
    const md::ObsSpec spec{};
    std::size_t offset = 0;
    // By reference: GCC's -Wrange-loop-construct flags the copy, where Clang
    // says nothing at all — and an ordinary Linux build is GCC's, since a build
    // takes the system compiler. Development runs on Clang, so this is one of
    // the diagnostics only the default build would ever show you.
    for (const auto& [slots, features] : std::array<std::pair<std::size_t, std::size_t>, 3>{
             {{spec.threats, md::ObsSpec::threat_features},
              {spec.interceptors, md::ObsSpec::interceptor_features},
              {spec.blasts, md::ObsSpec::blast_features}}}) {
        for (std::size_t i = 0; i < slots; ++i) {
            REQUIRE(samples.front().observation[offset + (i * features)] == 0.0F);
        }
        offset += slots * features;
    }
}

TEST_CASE("An illegal action is never chosen, whatever its logit says", "[unit][agent][policy]") {
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-policy.mdp"));
    const std::vector<Sample> samples = parity_samples();

    for (const Sample& sample : samples) {
        // Take the sample's own preferred action away and check the next choice
        // is still legal — the mask has to bind on every path, not only where
        // the fixture happened to exercise it.
        std::vector<std::uint8_t> legal = sample.legal;
        legal[sample.action] = 0u;
        bool anything_legal = false;
        for (const std::uint8_t flag : legal) {
            anything_legal = anything_legal || flag != 0u;
        }
        if (!anything_legal) {
            continue; // nothing left to choose; not a state the simulation makes
        }
        const md::agent::Policy::Decision decision = policy.act(sample.observation, legal);
        CHECK(decision.action != sample.action);
        CHECK(legal[decision.action] != 0u);
    }
}

TEST_CASE("Ties go to the lowest index", "[unit][agent][policy]") {
    // Two standard libraries agreeing about `argmax` today is not a property to
    // build a determinism claim on, so both sides promise it explicitly.
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-policy.mdp"));
    const std::vector<float> observation(policy.observation_size(), 0.0F);
    std::vector<std::uint8_t> legal(policy.action_count(), 1u);
    std::vector<float> logits(policy.action_count());

    const md::agent::Policy::Decision first = policy.act(observation, legal, logits);
    // Flatten the logits so every action is a tie, by masking all but two with
    // equal values — done through the public surface: give the same observation
    // twice and require the same answer, then take the winner away.
    const std::uint32_t winner = first.action;
    legal[winner] = 0u;
    const md::agent::Policy::Decision second = policy.act(observation, legal);
    CHECK(second.action != winner);
    CHECK(policy.act(observation, legal).action == second.action); // deterministic
}

TEST_CASE("A wrongly sized observation or mask is refused rather than read",
          "[unit][agent][policy]") {
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-policy.mdp"));
    const std::vector<float> short_observation(policy.observation_size() - 1, 0.0F);
    const std::vector<std::uint8_t> legal(policy.action_count(), 1u);
    CHECK_THROWS_AS(policy.act(short_observation, legal), md::agent::Policy::Error);

    const std::vector<float> observation(policy.observation_size(), 0.0F);
    const std::vector<std::uint8_t> short_legal(policy.action_count() - 1, 1u);
    CHECK_THROWS_AS(policy.act(observation, short_legal), md::agent::Policy::Error);
}

TEST_CASE("A file that is not a policy is refused", "[unit][agent][policy]") {
    CHECK_THROWS_AS(md::agent::Policy::load("no-such-file.mdp"), md::agent::Policy::Error);

    const std::vector<char> junk{'n', 'o', 't', ' ', 'a', ' ', 'p', 'o', 'l', 'i', 'c', 'y'};
    CHECK_THROWS_AS(md::agent::Policy::load(scratch("junk.mdp", junk)), md::agent::Policy::Error);

    CHECK_THROWS_AS(md::agent::Policy::load(scratch("empty.mdp", {})), md::agent::Policy::Error);
}

TEST_CASE("A truncated policy file is refused", "[unit][agent][policy]") {
    std::vector<char> bytes = read_all(fixture("tiny-policy.mdp"));
    REQUIRE(bytes.size() > 64u);
    bytes.resize(bytes.size() - 40);
    CHECK_THROWS_AS(md::agent::Policy::load(scratch("short.mdp", bytes)), md::agent::Policy::Error);
}

TEST_CASE("A corrupt payload is refused by its checksum", "[unit][agent][policy]") {
    // One flipped bit in one weight. Without the checksum this is a policy that
    // plays very slightly worse and nobody ever finds out why.
    std::vector<char> bytes = read_all(fixture("tiny-policy.mdp"));
    REQUIRE(!bytes.empty());
    bytes.back() = static_cast<char>(bytes.back() ^ 0x01);
    CHECK_THROWS_AS(md::agent::Policy::load(scratch("corrupt.mdp", bytes)),
                    md::agent::Policy::Error);
}

TEST_CASE("The failure message names the file and the check", "[unit][agent][policy]") {
    // Thrown at a person whose download went wrong. "Policy::Error" alone sends
    // them to the source; the filename and the failed check are the diagnosis.
    std::vector<char> bytes = read_all(fixture("tiny-policy.mdp"));
    bytes.back() = static_cast<char>(bytes.back() ^ 0x01);
    const std::filesystem::path broken = scratch("named.mdp", bytes);
    try {
        (void) md::agent::Policy::load(broken);
        FAIL("a corrupt policy loaded");
    } catch (const md::agent::Policy::Error& error) {
        const std::string message{error.what()};
        CHECK(message.find("named.mdp") != std::string::npos);
        CHECK(message.find("checksum") != std::string::npos);
    }
}

TEST_CASE("A policy trained against a different simulation is refused, not run",
          "[unit][agent][policy]") {
    // The exact state every checkpoint in this project was in on 2026-07-26: the
    // observation grew a feature (blast lifetime phase, 64 slots => +64 floats)
    // and every policy trained before it became unrunnable. Silently feeding one
    // a shorter observation would give an agent that plays like noise and no
    // indication why, so the driver refuses at construction — which is also
    // before the game has started a round nobody is driving.
    const md::agent::Policy policy = md::agent::Policy::load(fixture("tiny-policy.mdp"));
    const md::ObsSpec current{}; // the real simulation, far wider than the fixture
    CHECK_THROWS_AS(md::agent::PolicyDriver(policy, current), md::agent::Policy::Error);
}
