# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jens Köhler
# Assisted-by: Claude Code (Anthropic)
"""Generated by tools/protocol.py from protocol.toml. Do not edit.

See protocol.toml for what each value means and why it is the value it is.
"""

from __future__ import annotations

DECISION_INTERVAL: int = 4
MAX_TICKS: int = 120000
AIM_TRAIL: float = 0.877
PER_SPLIT: int = 32
VALIDATION_OFFSET: int = 0
CANONICAL_OFFSET: int = 32
CANONICAL_SPLIT: str = "canonical"
VALIDATION_SPLIT: str = "validation"
INFERENCE_DEVICE: str = "cpu"
POLICY_MAGIC: str = "MDPOLICY"
POLICY_CONTAINER_VERSION: int = 1
RUNS_DIR: str = "runs"
MODELS_DIR: str = "models"
MATCHES_DIR: str = "matches"
