# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jens Köhler
# Assisted-by: Claude Code (Anthropic)
"""Install a git pre-commit hook that runs the full quality gate."""

from __future__ import annotations

import stat
import sys

from . import _util

HOOK = """\
#!/usr/bin/env python3
# Auto-generated by `poe install-hooks`. Runs the full quality gate.
import subprocess
import sys

sys.exit(subprocess.call(["poe", "check"]))
"""


def install() -> int:
    hooks_dir = _util.PROJECT_ROOT / ".git" / "hooks"
    if not hooks_dir.is_dir():
        print("error: .git/hooks not found (not a git checkout?)", file=sys.stderr)
        return 1
    hook = hooks_dir / "pre-commit"
    hook.write_text(HOOK, encoding="utf-8")
    hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"installed git pre-commit hook: {hook}")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if args and args[0] == "install":
        return install()
    print("usage: python -m tools.hooks install", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
