# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jens Köhler
# Assisted-by: Claude Code (Anthropic)
"""Regenerate the `.mdp` fixture the native policy tests read.

    python -m tools.make_policy_fixture

**Checked in rather than generated at build time**, deliberately. The C++ tests
must not need a Python interpreter to run — `ctest` is the gate on three
platforms and two of them have no `md` installed — and more importantly, a
fixture computed by both sides at build time is two implementations of the same
bug. The point of these files is that one language wrote them and the other has
to agree.

They are small (a few kB) and change only when the format or the reference
forward pass changes, which is exactly when a reviewer should see the diff.

No torch anywhere: the weights come from a seeded generator and go straight
through `md.policy_format`, so this runs on any machine and produces the same
bytes on all of them.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from md import export_policy, policy_format

#: Small enough to read in a diff, wide enough that a transposed matrix cannot
#: pass: every dimension is different, so a swapped pair changes the shape.
OBSERVATION = 12
ACTIONS = 7
HIDDEN = 5

#: Fixed, because the fixture is a checked-in artifact and a regeneration that
#: changed every byte would make its diff useless.
SEED = 20260726

FIXTURES = Path(__file__).resolve().parents[1] / "agent" / "tests" / "fixtures"
POLICY = "tiny-policy.mdp"
PARITY = "tiny-policy-parity.json"


def build() -> policy_format.NativePolicy:
    rng = np.random.default_rng(SEED)

    def normal(*shape: int) -> np.ndarray:
        return (rng.standard_normal(shape) * 0.5).astype(np.float32)

    return policy_format.NativePolicy(
        schema=policy_format.SCHEMA,
        observation_size=OBSERVATION,
        action_count=ACTIONS,
        architecture="mlp",
        tensors=(
            policy_format.Tensor(
                "trunk.0.weight", (HIDDEN, OBSERVATION), normal(HIDDEN, OBSERVATION)
            ),
            policy_format.Tensor("trunk.0.bias", (HIDDEN,), normal(HIDDEN)),
            policy_format.Tensor("trunk.2.weight", (HIDDEN, HIDDEN), normal(HIDDEN, HIDDEN)),
            policy_format.Tensor("trunk.2.bias", (HIDDEN,), normal(HIDDEN)),
            policy_format.Tensor(
                "policy_head.weight", (ACTIONS, HIDDEN), normal(ACTIONS, HIDDEN)
            ),
            policy_format.Tensor("policy_head.bias", (ACTIONS,), normal(ACTIONS)),
            policy_format.Tensor("value_head.weight", (1, HIDDEN), normal(1, HIDDEN)),
            policy_format.Tensor("value_head.bias", (1,), normal(1)),
        ),
        # A display name, because `agent/tests/unit/test_policy.cpp` asserts the
        # native reader surfaces it — that is what puts a name rather than a
        # path on the game's HUD while a model plays.
        metadata={
            "display_name": "Tiny Fixture",
            "note": "generated by tools/make_policy_fixture.py; do not hand-edit",
            "trained_updates": 0,
        },
    )


def main() -> int:
    FIXTURES.mkdir(parents=True, exist_ok=True)
    written = policy_format.write(FIXTURES / POLICY, build())
    export_policy.write_parity_fixture(written, FIXTURES / PARITY, samples=12, seed=SEED)
    print(f"wrote {written} and {FIXTURES / PARITY}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
