# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jens Köhler
# Assisted-by: Claude Code (Anthropic)
"""Generate the C++ and Python copies of `protocol.toml`.

    python -m tools.protocol           # write both files
    python -m tools.protocol --check   # fail if either is out of date

The project cannot share a variable between its halves: the game is C++ and
never loads Python, and `md.benchmark` is deliberately importable without the
native extension so the console works in a package that does not ship one. So
the numbers exist twice — but written by this, from one source, and verified by
`poe check` rather than by anyone remembering.

**The generated files are committed.** Generating them only at build time would
mean a fresh checkout could not import `md.benchmark` until something had been
compiled, and would put a build step between a reader and a constant.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from collections.abc import Sequence
from pathlib import Path

from . import _util

SOURCE = _util.PROJECT_ROOT / "protocol.toml"
CPP_OUT = _util.PROJECT_ROOT / "core" / "include" / "md" / "protocol.hpp"
PY_OUT = _util.PROJECT_ROOT / "python" / "md" / "_protocol.py"

BANNER = "Generated by tools/protocol.py from protocol.toml. Do not edit."

#: How each value is spelled in C++. Kept beside the source rather than guessed
#: from the Python type, because `4` wants to be a `std::uint32_t` and not an
#: `int`, and a wrong integer type here is a conversion warning in every
#: consumer under this project's `-Wconversion`.
CPP_TYPES = {
    "decision_interval": "std::uint32_t",
    "max_ticks": "std::uint64_t",
    "reaction_delay": "std::uint32_t",
    "per_split": "std::size_t",
    "validation_offset": "std::size_t",
    "canonical_offset": "std::size_t",
    "policy_container_version": "std::uint32_t",
    "aim_trail": "float",
}


def _load() -> dict[str, dict[str, object]]:
    with SOURCE.open("rb") as handle:
        return tomllib.load(handle)


def _flatten(data: dict[str, dict[str, object]]) -> list[tuple[str, object]]:
    """Every entry as `(name, value)`, section prefixes dropped.

    The sections group the file for a reader; the names are unique across it, and
    a generated `md::protocol::seeds_per_split` would read worse than
    `md::protocol::per_split` does in context.
    """
    flat: list[tuple[str, object]] = []
    for section in data.values():
        flat.extend(section.items())
    names = [name for name, _ in flat]
    duplicates = {name for name in names if names.count(name) > 1}
    if duplicates:
        raise SystemExit(f"error: {SOURCE.name} defines {sorted(duplicates)} more than once")
    return flat


def _cpp(data: dict[str, dict[str, object]]) -> str:
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2026 Jens Köhler",
        "// Assisted-by: Claude Code (Anthropic)",
        f"// {BANNER}",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "/// The evaluation protocol. See protocol.toml for what each value means",
        "/// and why it is the value it is.",
        "namespace md::protocol {",
        "",
    ]
    for name, value in _flatten(data):
        if isinstance(value, float):
            lines.append(f"inline constexpr float {name} = {value}f;")
        elif isinstance(value, str):
            lines.append(f'inline constexpr std::string_view {name} = "{value}";')
        else:
            lines.append(f"inline constexpr {CPP_TYPES[name]} {name} = {value};")
    lines += ["", "} // namespace md::protocol", ""]
    return "\n".join(lines)


def _python(data: dict[str, dict[str, object]]) -> str:
    lines = [
        "# SPDX-License-Identifier: MIT",
        "# Copyright (c) 2026 Jens Köhler",
        "# Assisted-by: Claude Code (Anthropic)",
        f'"""{BANNER}',
        "",
        "See protocol.toml for what each value means and why it is the value it is.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for name, value in _flatten(data):
        rendered = f'"{value}"' if isinstance(value, str) else repr(value)
        kind = "str" if isinstance(value, str) else "float" if isinstance(value, float) else "int"
        lines.append(f"{name.upper()}: {kind} = {rendered}")
    lines.append("")
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.protocol")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if a generated file differs from protocol.toml",
    )
    args = parser.parse_args(argv)

    data = _load()
    wanted = {CPP_OUT: _cpp(data), PY_OUT: _python(data)}

    stale: list[Path] = []
    for path, text in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"  wrote {path.relative_to(_util.PROJECT_ROOT)}")

    if stale:
        names = ", ".join(str(p.relative_to(_util.PROJECT_ROOT)) for p in stale)
        print(
            f"error: {names} does not match protocol.toml.\n"
            "       Run `poe protocol` and commit the result. These files are\n"
            "       generated; editing them by hand is how the two halves of the\n"
            "       project end up disagreeing about what a score means.",
            file=sys.stderr,
        )
        return 1
    if not args.check:
        print("protocol: up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
